name: Sphinx docs to gh-pages

on:
  workflow_dispatch:

env:
  SPHINXWORKING: True

jobs:
  sphinx_docs_to_gh-pages:
    runs-on: ubuntu-latest
    name: Sphinx docs to gh-pages
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Additional info about the build
        shell: bash
        run: |
          uname -a

      - name: Setup conda env
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: devtools/conda-envs/docs_env.yaml
          environment-name: docs
          condarc: |
            channels:
              - uibcdf
              - conda-forge
              - ambermd
              - defaults
            channel_priority: strict
          create-args: >-
            python=3.10

      - name: Info conda
        shell: bash -l {0}
        run: |
          micromamba info
          micromamba list

      - name: Running the Sphinx to gh-pages Action
        uses: uibcdf/action-sphinx-docs-to-gh-pages@v2.0.0

